# dataclasses for halftest

import datetime
import typing


import dataclasses
from typing import TypedDict, Optional, List, Any
from half_orm.field import Field

class DC_Relation:
    # auto-generated by half-orm-dev — do not edit

    @classmethod
    async def ho_acopy(cls, data, columns=None) -> int:
        """Async variant of :meth:`ho_copy`. *Executes SQL.*

        Requires an async connection opened with ``await model.aconnect()``.

        *New in version 0.18.12.*
        """
        ...

    async def ho_acount(self, *args, distinct: bool = False) -> int:
        """Async variant of ho_count. *Executes SQL.*

        *New in version 0.18.0.*
        """
        ...

    async def ho_adelete(self, *args, delete_all=False):
        """Async variant of ho_delete. *Executes SQL.*

        *New in version 0.18.0.*
        """
        ...

    async def ho_aget(self, *args: str) -> dict:
        """Async variant of ho_get. *Executes SQL.*

        Issues a single ``SELECT … LIMIT 2`` query and returns the matching
        row as a plain ``dict``.

        Args:
            *args: optional column names to select.  If omitted, all columns
                are returned.

        Returns:
            dict: the matching row.

        Raises:
            NotFoundError: no row matches the predicate.
            MultipleRowsError: more than one row matches the predicate.

        *New in version 1.0.0.*
        """
        ...

    async def ho_ainsert(self, *args, upsert=False) -> dict:
        """Async variant of ho_insert. *Executes SQL.*

        *New in version 0.18.0.*
        """
        ...

    async def ho_ais_empty(self) -> bool:
        """Async variant of ho_is_empty. *Executes SQL.*

        *New in version 0.18.0.*
        """
        ...

    async def ho_aselect(self, *args, distinct: bool = False, order_by: str = None, limit: int = None, offset: int = None):
        """Async variant of ho_select. Returns a list of dicts (not a generator). *Executes SQL.*

        *New in version 0.18.0.*
        """
        ...

    def ho_assert_is_singleton(self):
        """Assert that this predicate identifies exactly one row, without querying the database.

        A predicate is a *singleton* when:

        * every field of a unique identifier (primary key or any
          ``UNIQUE NOT NULL`` constraint) is set with the ``=`` comparator, **or**
        * a FK join constrains a unique identifier of this relation: the fields
          on *this* side of the join form a PK or UNIQUE NOT NULL, and the
          corresponding fields on the joined relation are all fixed with ``=``.

        The check is purely structural — no SQL is executed.

        Returns:
            self — for chaining before a write operation.

        Raises:
            NotASingletonError: if no unique identifier is fully set.

        Example:
            ho_is_singleton usage:
                ```python
                # OK — id is the primary key
                Author(id=42).ho_assert_is_singleton()

                # OK — email has a UNIQUE NOT NULL constraint
                Author(email='alice@example.com').ho_assert_is_singleton()

                # Raises — last_name is not a unique identifier
                Author(last_name='Martin').ho_assert_is_singleton()

                # OK — FK navigation: comment.post_id fixes post.id (PK)
                Comment(post_id=42).fk_post().ho_assert_is_singleton()

                # Typical usage: guard a single-row write
                Author(id=42).ho_assert_is_singleton().ho_update(email='new@example.com')

                # Via FK navigation: delete the post linked to a specific comment
                Comment(post_id=42).fk_post().ho_assert_is_singleton().ho_delete()
                ```

        *New in version 0.18.0.*
        """
        ...

    async def ho_aupdate(self, *args, update_all=False, **kwargs):
        """Async variant of ho_update. *Executes SQL.*

        *New in version 0.18.0.*
        """
        ...

    def ho_cast(self, qrn):
        """Cast a relation to a related relation in the PostgreSQL inheritance hierarchy.

        The target ``qrn`` must either be an ancestor or a descendant of this
        relation in the PostgreSQL table-inheritance hierarchy.  The check is
        performed via the Python MRO, which :mod:`half_orm.relation_factory`
        builds to mirror the PostgreSQL hierarchy.

        Args:
            qrn (str): qualified relation name of the target (e.g. ``'blog.event'``).

        Returns:
            Relation: a new instance of the target class carrying the same
            field constraints and join state as ``self``.

        Raises:
            CastError: if ``qrn`` is not related to this relation by inheritance.
        """
        ...

    @classmethod
    def ho_copy(cls, data, columns=None) -> int:
        """Load rows into the table using PostgreSQL ``COPY FROM``. *Executes SQL.*

        Much faster than repeated :meth:`ho_insert` calls for bulk loads.
        No ``RETURNING`` is supported — the number of inserted rows is returned
        instead.

        *New in version 0.18.12.*

        Args:
            data: either a ``list[dict]`` (column names are taken from the keys
                of the first dict) or a file-like object opened in text mode
                (CSV with a header row, or headerless if ``columns`` is given).
            columns (list[str] | None): explicit column list. Required when
                *data* is a headerless file-like object; ignored when *data* is
                a ``list[dict]``.

        Returns:
            int: number of rows inserted.

        Raises:
            ReadOnlyRelationError: if the relation is a view or other
                non-writable kind.
            ValueError: if *data* is empty or *columns* is required but missing.

        Example:
            From a list of dicts:
                ```python
                n = Author.ho_copy([
                    {'first_name': 'Bob', 'last_name': 'Martin',
                     'birth_date': date(1980, 1, 1)},
                    {'first_name': 'Eve', 'last_name': 'Dupont',
                     'birth_date': date(1990, 5, 12)},
                ])
                print(n)  # 2
                ```

            From a CSV file (with header row):
                ```python
                with open('authors.csv') as f:
                    n = Author.ho_copy(f)
                ```

            From a headerless CSV file:
                ```python
                with open('authors_no_header.csv') as f:
                    n = Author.ho_copy(
                        f,
                        columns=['first_name', 'last_name', 'birth_date'],
                    )
                ```
        """
        ...

    def ho_count(self, *args, distinct: bool = False):
        """Return the number of rows that satisfy the predicate. *Executes SQL.*

        Args:
            *args: column names for the inner SELECT (useful with
                ``distinct=True``).
            distinct (bool): if ``True``, count only distinct tuples.
                Default: ``False``.

        Returns:
            int: the cardinality of the extension.

        Example:
            ho_count usage:
                ```python
                Author().ho_count()                    # total number of authors
                Author(last_name='Martin').ho_count()  # subset cardinality
                ```

        *New in version 0.18.0:* ``distinct`` parameter.
        """
        ...

    def ho_delete(self, *args, delete_all=False):
        """Remove every row that satisfies the predicate. *Executes SQL.*

        Args:
            *args: column names to return from the deleted rows. Pass
                ``'*'`` to return all columns.
            delete_all (bool): must be ``True`` when no primary key field
                is set, as a safety guard against accidental mass deletions.
                Default: ``False``.

        Returns:
            list[dict] | None: the deleted rows if ``*args`` was provided,
            otherwise ``None``.

        Raises:
            RuntimeError: if the predicate is not set and ``delete_all``
                is ``False``.

        Example:
            ho_delete usage:
                ```python
                # Delete one identified row
                Author(id=99).ho_assert_is_singleton().ho_delete()

                # Delete all posts for a given author
                Post(author_id=1).ho_delete()

                # Delete all posts
                Post().ho_delete(delete_all=True)
                ```
        """
        ...

    @classmethod
    def ho_description(cls):
        """Returns the description (comment) of the relation

        """
        ...

    def ho_dict(self):
        """Returns a dictionary containing only the values of the fields
        that are set.
        """
        ...

    def ho_freeze(self):
        """set _ho_isfrozen to True."""
        ...

    def ho_get(self, *args: str) -> dict:
        """Fetch the single row matching this predicate from the database. *Executes SQL.*

        Guarantees that the predicate matches exactly one row and returns it as
        a plain ``dict`` mapping column names to their Python values.
        Issues a single ``SELECT … LIMIT 2`` query.

        Args:
            *args: optional column names to select.  If omitted, all columns
                are returned.

        Returns:
            dict: the matching row.

        Raises:
            NotFoundError: no row matches the predicate.
            MultipleRowsError: more than one row matches the predicate.

        Example:
            ho_get usage:
                ```python
                row = Person(last_name='Lagaffe', first_name='Gaston').ho_get()
                print(row['id'], row['last_name'])
                ```

        *Changed in version 1.0.0* **(breaking)**: returns a ``dict`` instead
        of a ``Relation`` object.  Raises :exc:`NotFoundError` or
        :exc:`MultipleRowsError` instead of the generic :exc:`ExpectedOneError`.
        """
        ...

    def ho_insert(self, *args, upsert: Optional[bool] = False) -> '[dict]':
        """Insert the row described by this predicate. *Executes SQL.*

        Args:
            *args: column names to include in the returned dict. If omitted,
                all columns are returned (equivalent to ``RETURNING *``).
            upsert (bool): add ``ON CONFLICT DO UPDATE`` to the INSERT. Default: ``False``.

        Returns:
            dict: the inserted row.

        Raises:
            ReadOnlyRelationError: if the relation is a view or other
                non-writable kind.

        Example:
            Insert an author:
                ```python
                alice = Author(
                    first_name='Alice', last_name='Martin',
                    email='alice@example.com',
                ).ho_insert()
                alice['id']   # 1
                ```
        """
        ...

    def ho_is_empty(self):
        """Return ``True`` if the extension is empty, ``False`` otherwise. *Executes SQL.*

        Returns:
            bool

        Example:
            ho_is_empty usage:
                ```python
                Author(last_name='Unknown').ho_is_empty()  # True if no such author
                ```
        """
        ...

    def ho_is_set(self):
        """Return True if one field at least is set or if self has been
        constrained by at least one of its foreign keys or self is the
        result of a combination of Relations (using set operators) where
        at least one operand is itself constrained.
        """
        ...

    def ho_mogrify(self):
        """Print the SQL SELECT that would be executed and return ``self``.

        Activates SQL tracing for the next query on this object. The query
        is printed to stderr when the next executor is called. Useful for
        debugging predicate composition.

        Returns:
            self — for chaining.

        Example:
            ```python
            Author(last_name='Martin').ho_mogrify().ho_count()
            ```
            displays:
            ```sql
            select
            count(*) from (select
            r... .*
            from
            "blog"."author" as r...
            where
                (r... ."name" = 'Martin'::text)) as ho_count
            ```
        """
        ...

    def ho_select(self, *args, distinct: bool = False, order_by: str = None, limit: int = None, offset: int = None, json_agg=None):
        """Enumerate the extension of this predicate. *Executes SQL.*

        This method is a generator. Without arguments it is equivalent to
        iterating directly on the relation object (``for row in rel:``).

        Args:
            *args: column names to project. If omitted, all columns are
                returned.
            distinct (bool): add ``DISTINCT`` to the SELECT. Default: ``False``.
            order_by (str): SQL ``ORDER BY`` clause, e.g.
                ``'last_name, first_name desc'``. Default: ``None``.
            limit (int): maximum number of rows to return. Default: ``None``.
            offset (int): number of rows to skip. Default: ``None``.
            json_agg (dict): aggregate already-set fkeys as JSON arrays via
                a ``LEFT JOIN`` + ``json_agg`` + ``GROUP BY`` on the primary key.

                Each entry maps a fkey attribute name to its spec:

                - ``[field, ...]`` — list of column names; alias = fkey attr name.
                - ``{'fields': [...], 'alias': 'name'}`` — explicit alias.
                - ``[]`` — empty list returns all columns via ``row_to_json``.
                - ``{'fields': [...], 'alias': 'name', 'distinct': True}`` —
                  deduplicate aggregated rows using a correlated subquery
                  (``SELECT DISTINCT … FROM … WHERE join_cond``) instead of a
                  LEFT JOIN.  Avoids duplicates produced by intermediate JOIN
                  multiplications.  Default: ``False``.

                The fkey must have been set via ``.fk_attr.set(rel)`` before
                calling ``ho_select``.

                The type of the aggregated value depends on the FK direction:

                - **reverse FK, non-unique** (one-to-many): a ``list`` of dicts,
                  empty (``[]``) when no related rows exist.
                - **reverse FK, unique** (one-to-one via UNIQUE or PK constraint):
                  a single ``dict``, or ``None`` when no related row exists.
                - **direct FK** (many-to-one): a single ``dict``, or ``None``
                  when the FK target is absent (nullable FK).

        Yields:
            dict: one row of the extension.

        Example:
            Project and sort:
                ```python
                for row in Author(last_name='Martin').ho_select('id', 'email', order_by='id'):
                    print(row)   # {'id': 1, 'email': 'alice@example.com'}
                ```

            Aggregate related rows as JSON (reverse FK):
                ```python
                alice = Author(last_name='Martin')
                alice.post_rfk.set()   # join all posts
                for row in alice.ho_select(json_agg={'post_rfk': ['id', 'title']}):
                    print(row['post_rfk'])  # [{'id': 1, 'title': '...'}, ...]
                ```

            Chained FK (A ← B → C) — aggregate the leaf relation's data:
                ```python
                # For each post, collect the persons who commented on it.
                # post ← comment → person  (comment is the junction)
                post = Post(title='Hello')
                comment = Comment()
                comment.author_fk.set()   # chain: comment → person
                post.comment_rfk.set(comment)
                for row in post.ho_select(json_agg={'comment_rfk': ['last_name']}):
                    print(row['comment_rfk'])  # [{'last_name': '...'}, ...]
                ```

        *New in version 0.18.0:* ``distinct``, ``order_by``, ``limit`` and ``offset`` parameters.

        *New in version 0.18.6:* ``json_agg`` parameter.

        *Changed in version 0.18.7* **(breaking)**: direct FK and singleton reverse FK (UNIQUE/PK) in ``json_agg`` return a ``dict`` (or ``None``) instead of a list.
        """
        ...

    def ho_unaccent(self, *fields_names):
        """Sets unaccent for each field listed in fields_names"""
        ...

    def ho_unfreeze(self):
        """Allow to add attributs to a relation"""
        ...

    def ho_update(self, *args, update_all=False, **kwargs):
        """Update every row that satisfies the predicate. *Executes SQL.*

        Args:
            *args: column names to return from the updated rows. Pass
                ``'*'`` to return all columns. If omitted, nothing is returned.
            update_all (bool): must be ``True`` when ``self`` has no
                constraint set, to confirm the intent to update all rows.
                Default: ``False``.
            **kwargs: ``{column_name: new_value}`` pairs to apply.
                ``None`` values are silently ignored.

        Returns:
            list[dict] | None: the updated rows if ``*args`` was provided,
            otherwise ``None``.

        Raises:
            RuntimeError: if no constraint is set and ``update_all`` is
                ``False``.

        Example:
            ho_update usage:
                ```python
                # Update a single row — guarded by singleton check
                Author(id=1).ho_assert_is_singleton().ho_update(email='new@example.com')

                # Update an entire subset at once
                Post(author_id=99).ho_update(content='[archived]')
                ```
        """
        ...

    def ho_where_display(self):
        """Returns the predicate as a (possibly nested) dict, or ``None`` if unconstrained.

        Every node in the tree — leaf, compound, or negation — always carries:

        - ``'tables'``: ``set[str]`` — all ``schema.table`` names involved
          (leaf: derived from the SQL AST; compound/neg: union of children).
        - ``'constraints'``: ``list[dict]`` — all leaf constraints, each with
          keys ``relation``, ``field``, ``comp``, ``value``
          (leaf: own fields; compound/neg: concatenation of children).

        A **leaf** node additionally has ``'joins'``, ``'where'``, ``'values'``.

        A **compound** node (``|``, ``&``, ``-``) additionally has
        ``'operator'`` (``'or'``, ``'and'``, ``'and not'``),
        ``'left'``, and ``'right'``.

        A **negation** node (``~``) additionally has ``'operator': 'neg'``
        and ``'operand'``.

        Returns:
            dict | None: the predicate structure, or ``None`` if the relation
            has no constraint set.

        *New in version 0.18.0.*
        """
        ...

@dataclasses.dataclass
class DC_ActorPerson(DC_Relation):
    id: int = dataclasses.field(default=None)
    first_name: str = dataclasses.field(default=None)
    last_name: str = dataclasses.field(default=None)
    birth_date: datetime.date = dataclasses.field(default=None)
    def __post_init__(self):
        self.id: Field = None
        self.first_name: Field = None
        self.last_name: Field = None
        self.birth_date: Field = None

@dataclasses.dataclass
class DC_BlogComment(DC_Relation):
    id: int = dataclasses.field(default=None)
    content: str = dataclasses.field(default=None)
    post_id: int = dataclasses.field(default=None)
    author_id: int = dataclasses.field(default=None)
    column5: str = dataclasses.field(default=None)
    tags: str = dataclasses.field(default_factory=list)
    def __post_init__(self):
        self.id: Field = None
        self.content: Field = None
        self.post_id: Field = None
        self.author_id: Field = None
        self.column5: Field = None
        self.tags: Field = None

@dataclasses.dataclass
class DC_BlogEvent(DC_Relation):
    id: int = dataclasses.field(default=None)
    title: str = dataclasses.field(default=None)
    content: str = dataclasses.field(default=None)
    author_first_name: str = dataclasses.field(default=None)
    author_last_name: str = dataclasses.field(default=None)
    author_birth_date: datetime.date = dataclasses.field(default=None)
    data: typing.Any = dataclasses.field(default=None)
    begin: datetime.datetime = dataclasses.field(default=None)
    end: datetime.datetime = dataclasses.field(default=None)
    location: str = dataclasses.field(default=None)
    def __post_init__(self):
        self.id: Field = None
        self.title: Field = None
        self.content: Field = None
        self.author_first_name: Field = None
        self.author_last_name: Field = None
        self.author_birth_date: Field = None
        self.data: Field = None
        self.begin: Field = None
        self.end: Field = None
        self.location: Field = None

@dataclasses.dataclass
class DC_BlogPost(DC_Relation):
    id: int = dataclasses.field(default=None)
    title: str = dataclasses.field(default=None)
    content: str = dataclasses.field(default=None)
    author_first_name: str = dataclasses.field(default=None)
    author_last_name: str = dataclasses.field(default=None)
    author_birth_date: datetime.date = dataclasses.field(default=None)
    data: typing.Any = dataclasses.field(default=None)
    def __post_init__(self):
        self.id: Field = None
        self.title: Field = None
        self.content: Field = None
        self.author_first_name: Field = None
        self.author_last_name: Field = None
        self.author_birth_date: Field = None
        self.data: Field = None

@dataclasses.dataclass
class DC_BlogViewPostComment(DC_Relation):
    post_title: str = dataclasses.field(default=None)
    author_post_id: int = dataclasses.field(default=None)
    author_post_first_name: str = dataclasses.field(default=None)
    author_post_last_name: str = dataclasses.field(default=None)
    comment_id: int = dataclasses.field(default=None)
    comment_content: str = dataclasses.field(default=None)
    post_id: int = dataclasses.field(default=None)
    author_comment_id: int = dataclasses.field(default=None)
    author_comment_first_name: str = dataclasses.field(default=None)
    author_comment_last_name: str = dataclasses.field(default=None)
    def __post_init__(self):
        self.post_title: Field = None
        self.author_post_id: Field = None
        self.author_post_first_name: Field = None
        self.author_post_last_name: Field = None
        self.comment_id: Field = None
        self.comment_content: Field = None
        self.post_id: Field = None
        self.author_comment_id: Field = None
        self.author_comment_first_name: Field = None
        self.author_comment_last_name: Field = None
